version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            python manage.py test
      - store_test_results:
          path: test-results
